version: '3.8'

services:
  backend:
    build: ./backend
    container_name: workhub-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_j4WT9JuyPwgk@ep-royal-lab-a1t6h3fg-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?ssl=require
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=workhub-uploads
      - SECRET_KEY=supersecretkey
    depends_on:
      redis:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - workhub-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: workhub-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    command: npm run dev
    depends_on:
      - backend
    networks:
      - workhub-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  agent_service:
    build: ./langgraph
    container_name: workhub-agent
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=http://backend:8000
    depends_on:
      - redis
      - backend
    networks:
      - workhub-network
    volumes:
      - ./langgraph:/app

  #   postgres:
  #     image: postgres:15-alpine
  #     container_name: workhub-postgres
  #     restart: always
  #     ports:
  #       - "5432:5432"
  #     environment:
  #       - POSTGRES_USER=user
  #       - POSTGRES_PASSWORD=password
  #       - POSTGRES_DB=workhub
  #     healthcheck:
  #       test: [ "CMD-SHELL", "pg_isready -U user -d workhub" ]
  #       interval: 5s
  #       timeout: 5s
  #       retries: 5
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     networks:
  #       - workhub-network

  redis:
    image: redis:7-alpine
    container_name: workhub-redis
    ports:
      - "6379:6379"
    networks:
      - workhub-network

  minio:
    image: minio/minio
    container_name: workhub-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - workhub-network

networks:
  workhub-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
